### PR TITLE
removed search button and updated search input styles

### PR DESCRIPTION
**Pull request by jocelynjeffrey**

### CODE REVIEW

**Review by astr0-4 — CHANGES_REQUESTED** [review]
looks good @jocelynjeffrey!
Can you also replace the form element with a div in `SearchBar.js`? 
Also, what do you think about making the placeholder text grey instead of black?

**Comment by jocelynjeffrey** [comment]
I've updated the form to a div (good call) but I'm not sure about the grey placeholder. It looks a little washed-out to me. What do you guys think?
screen shot 2017-08-13 at 1 49 36 pm

**Comment by jocelynjeffrey** [comment]
Sounds good @astr0-4 !

**Review by ghost — APPROVED** [review]
LGTM!

**Review by astr0-4 — APPROVED** [review]
looks good!!! 🍺  💯

**Pull request merged**
