### PR TITLE
updated store address and contact information

### PR DESCRIPTION
**Pull request by jocelynjeffrey**
Hey team - I updated the contact information we're displaying for the stores. Hours TBD (see slack for notes on LCBO's strange clock)

### CODE REVIEW

**Review by astr0-4 — COMMENTED** [review]
Hey @jocelynjeffrey, do we need the Address, Distance, and Telephone labels? The designs on Trello don't have them: 
screen shot 2017-08-17 at 8 38 06 am

**Comment by jocelynjeffrey** [comment]
@astr0-4 - ah yeah, we can take them if you guys don't like them. I think we should leave the label for distance in though - I think it's clear that we're measure distance from the user to the store, but the label helps with UX.

**Comment by astr0-4** [comment]
ok we can keep the distance one! 👍 👍

**Review by jprittie — APPROVED** [review]
LGTM

**Comment by astr0-4** [comment]
LGTM! 💯

**Review by astr0-4 — APPROVED** [review]

**Pull request merged**
